FROM openshift/origin-release:golang-1.16 as builder

# Add everything
ENV PKG_NAME=github.com/openshift-kni/resource-topology-exporter
ENV PKG_PATH=/go/src/$PKG_NAME
RUN mkdir -p $PKG_PATH

COPY . $PKG_PATH/
WORKDIR $PKG_PATH

RUN make

FROM registry.access.redhat.com/ubi8/ubi
COPY --from=builder /go/src/github.com/openshift-kni/resource-topology-exporter/_out/resource-topology-exporter /bin/resource-topology-exporter
RUN mkdir /etc/resource-topology-exporter/ && \
    touch /etc/resource-topology-exporter/config.yaml
ENTRYPOINT ["/bin/resource-topology-exporter"]
