resources:
  reservedcpus: "0"
  resourcemapping:
    "8086:1520": "intel_sriov_netdevice"
excludelist:
  masternode: [memory, device/exampleA]
  workernode1: [memory, device/exampleB]
  workernode2: [cpu]
  "*": [device/exampleC]
